In [2]:
import numpy as np

A = np.array([[1,2,3,4,5],[1,1,1,1,1],[2,3,4,5,6],[0,1,0,1,0]])
A

array([[1, 2, 3, 4, 5],
       [1, 1, 1, 1, 1],
       [2, 3, 4, 5, 6],
       [0, 1, 0, 1, 0]])

In [ ]:
Q1, R1 = np.linalg.qr(A)
R1.round(3)

In [4]:
Q2, R2 = np.linalg.qr(R1.T)
(Q1 @ R2.T @ Q2.T).round(3)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  3.,  4.,  5.,  6.],
       [-0.,  1., -0.,  1., -0.]])

In [5]:
R2.round(3)

array([[11.619, -2.84 , -2.556,  0.   ],
       [ 0.   , -0.966,  0.195, -0.   ],
       [ 0.   ,  0.   , -1.195,  0.   ],
       [ 0.   ,  0.   ,  0.   , -0.   ]])