In [33]:
import numpy as np

A = np.array([[1,2,3,4,5],[1,1,1,1,1],[2,3,4,5,6],[0,1,0,1,0]])
A

array([[1, 2, 3, 4, 5],
       [1, 1, 1, 1, 1],
       [2, 3, 4, 5, 6],
       [0, 1, 0, 1, 0]])

In [34]:
Q1, R1 = np.linalg.qr(A)
R1.round(3)

array([[-2.449, -3.674, -4.899, -6.124, -7.348],
       [ 0.   ,  1.225,  0.816,  2.041,  1.633],
       [ 0.   ,  0.   ,  1.155,  1.155,  2.309],
       [ 0.   ,  0.   ,  0.   , -0.   , -0.   ]])

In [35]:
Q2, R2 = np.linalg.qr(R1.T)
(Q1 @ R2.T @ Q2.T).round(3)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  3.,  4.,  5.,  6.],
       [-0.,  1., -0.,  1., -0.]])

In [36]:
R2.round(3)

array([[11.619, -2.84 , -2.556,  0.   ],
       [ 0.   , -0.966,  0.195, -0.   ],
       [ 0.   ,  0.   , -1.195,  0.   ],
       [ 0.   ,  0.   ,  0.   , -0.   ]])

Below are the bases U, V that we are after:

In [37]:
U = Q1
R = R2.T
V = Q2

Let's doublecheck that we did everything right. We should be able to reconstruct A as below (otherwise we did something wrong)

In [31]:
r = np.linalg.matrix_rank(A)

U1 = U[:,:r]
V1 = V[:,:r]
C = R[:r,:r]

In [32]:
Ahat = U1 @ C @ V1.T
Ahat.round(2)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  3.,  4.,  5.,  6.],
       [-0.,  1., -0.,  1., -0.]])